server:
  port: 8080
spring:
  application:
    name: member-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jeuksipay
    username: postgresuser
    password: root
  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
    show-sql: true
    database: postgresql
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
    serialization:
      fail-on-empty-beans: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
logging:
  config: classpath:logback-spring.xml
